import React, { useState } from 'react';
import { X, Lock, UserCheck, ShieldCheck, Smartphone, ArrowLeft, KeyRound, Loader2 } from 'lucide-react';
import { useAuthStore } from '../../stores/useAuthStore';

export const SetupLoginModal: React.FC = () => {
  const {
    isAuthModalOpen,
    setAuthModalOpen,
    authMode,
    login,
    setup,
    isInitialized,
    requires2fa,
    verify2fa,
    cancel2fa,
  } = useAuthStore();

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  // 2FA verification state
  const [otpCode, setOtpCode] = useState('');
  const [useBackupCode, setUseBackupCode] = useState(false);

  if (!isAuthModalOpen) return null;

  const isSetupMode = authMode === 'setup' || !isInitialized;

  const handlePasswordSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    if (!username.trim() || !password) {
      setError('Please fill out all fields');
      return;
    }

    if (isSetupMode) {
      if (password.length < 6) {
        setError('Password must be at least 6 characters long');
        return;
      }
      if (password !== confirmPassword) {
        setError('Passwords do not match');
        return;
      }
    }

    setIsLoading(true);
    try {
      if (isSetupMode) {
        await setup(username.trim(), password);
        setAuthModalOpen(false);
      } else {
        await login(username.trim(), password);
        // Note: if 2FA is required, useAuthStore sets requires2fa = true and keeps modal open
      }
    } catch (err: any) {
      setError(err.message || 'Authentication failed');
    } finally {
      setIsLoading(false);
    }
  };

  const handle2faSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    if (!otpCode.trim()) {
      setError(useBackupCode ? 'Please enter a recovery code' : 'Please enter the 6-digit code');
      return;
    }

    setIsLoading(true);
    try {
      await verify2fa(otpCode.trim());
      setAuthModalOpen(false);
      setOtpCode('');
      setUseBackupCode(false);
    } catch (err: any) {
      setError(err.message || 'Invalid verification code');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-in fade-in">
      <div
        onClick={(e) => e.stopPropagation()}
        className="bg-white dark:bg-[#252526] w-full max-w-sm rounded-xl shadow-2xl border border-gray-200 dark:border-[#333333] p-6 select-none"
      >
        {/* Modal Header */}
        <div className="flex items-center justify-between pb-3 border-b border-gray-200 dark:border-[#333333]">
          <div className="flex items-center gap-2 font-semibold text-sm text-gray-900 dark:text-gray-100">
            {requires2fa ? (
              <>
                <Smartphone size={18} className="text-blue-500" />
                <span>Two-Factor Authentication</span>
              </>
            ) : isSetupMode ? (
              <>
                <ShieldCheck size={18} className="text-blue-500" />
                <span>Initialize Admin Account</span>
              </>
            ) : (
              <>
                <Lock size={18} className="text-blue-500" />
                <span>Sign In to KV Files</span>
              </>
            )}
          </div>
          {isInitialized && !requires2fa && (
            <button
              onClick={() => setAuthModalOpen(false)}
              className="p-1 rounded text-gray-400 hover:text-gray-600 dark:hover:text-gray-200"
            >
              <X size={16} />
            </button>
          )}
        </div>

        {/* 2FA Challenge Form */}
        {requires2fa ? (
          <form onSubmit={handle2faSubmit} className="mt-4 space-y-4">
            <p className="text-xs text-gray-500 dark:text-gray-400">
              {useBackupCode
                ? 'Enter one of your emergency 8-character recovery backup codes:'
                : 'Enter the 6-digit code generated by your authenticator app:'}
            </p>

            <div>
              <input
                autoFocus
                type="text"
                placeholder={useBackupCode ? 'XXXX-XXXX' : '000000'}
                maxLength={useBackupCode ? 12 : 6}
                value={otpCode}
                onChange={(e) =>
                  setOtpCode(
                    useBackupCode ? e.target.value.toUpperCase() : e.target.value.replace(/\D/g, '')
                  )
                }
                className={`w-full py-2.5 px-3 bg-gray-50 dark:bg-[#1e1e1e] border-2 border-blue-500/60 rounded-lg text-gray-900 dark:text-gray-100 focus:outline-none focus:border-blue-600 text-center font-mono ${
                  useBackupCode ? 'text-sm tracking-widest' : 'text-xl tracking-[0.3em]'
                }`}
              />
            </div>

            {error && <div className="text-xs text-red-500 text-center">{error}</div>}

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-2 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white rounded text-xs font-semibold transition-colors flex items-center justify-center gap-1.5"
            >
              {isLoading && <Loader2 size={13} className="animate-spin" />}
              <span>Verify & Continue</span>
            </button>

            <div className="flex items-center justify-between pt-2 border-t border-gray-200 dark:border-[#333333] text-[11px]">
              <button
                type="button"
                onClick={() => {
                  setUseBackupCode(!useBackupCode);
                  setOtpCode('');
                  setError(null);
                }}
                className="text-blue-600 dark:text-blue-400 hover:underline flex items-center gap-1"
              >
                <KeyRound size={12} />
                <span>{useBackupCode ? 'Use Authenticator App' : 'Use Recovery Code'}</span>
              </button>

              <button
                type="button"
                onClick={() => {
                  cancel2fa();
                  setError(null);
                }}
                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 flex items-center gap-1"
              >
                <ArrowLeft size={12} />
                <span>Back</span>
              </button>
            </div>
          </form>
        ) : (
          /* Standard Username & Password Form */
          <form onSubmit={handlePasswordSubmit} className="mt-4 space-y-3">
            {isSetupMode && (
              <p className="text-xs text-gray-500">
                Welcome to KV Files! Configure your primary administrator credentials to secure this instance.
              </p>
            )}

            <div>
              <label className="text-xs text-gray-500 mb-1 block">Username</label>
              <input
                autoFocus
                type="text"
                placeholder="admin"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full text-xs p-2.5 bg-gray-50 dark:bg-[#1e1e1e] border border-gray-300 dark:border-gray-700 rounded text-gray-800 dark:text-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="text-xs text-gray-500 mb-1 block">Password</label>
              <input
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full text-xs p-2.5 bg-gray-50 dark:bg-[#1e1e1e] border border-gray-300 dark:border-gray-700 rounded text-gray-800 dark:text-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
              />
            </div>

            {isSetupMode && (
              <div>
                <label className="text-xs text-gray-500 mb-1 block">Confirm Password</label>
                <input
                  type="password"
                  placeholder="••••••••"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  className="w-full text-xs p-2.5 bg-gray-50 dark:bg-[#1e1e1e] border border-gray-300 dark:border-gray-700 rounded text-gray-800 dark:text-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500"
                />
              </div>
            )}

            {error && <div className="text-xs text-red-500 pt-1">{error}</div>}

            <div className="pt-2">
              <button
                type="submit"
                disabled={isLoading}
                className="w-full py-2 bg-blue-600 hover:bg-blue-700 disabled:opacity-40 text-white rounded text-xs font-semibold transition-colors flex items-center justify-center gap-1.5"
              >
                {isLoading ? (
                  'Processing...'
                ) : isSetupMode ? (
                  <>
                    <UserCheck size={14} />
                    <span>Create Admin & Launch</span>
                  </>
                ) : (
                  'Sign In'
                )}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
};
